openapi: 3.0.1
info:
  x-api-id: 95d54b6e-f662-4d8d-a06b-52992d476fdd
  title: HSRM Wallbox API
  description: >-
    This REST-API serves as a interface to a ISO-15118 SECC Server for vehicle to grid communication between an electric vehicle and a charging station. Over this API new charging sessions can be created and controlled. The API propeses methods to control the charging parameters during a charging session.
  contact:
    name: Fabian Birk
    email: fabian.birk@student.hs-rm.de
    url: https://github.com/fbirk
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 0.0.1
externalDocs:
  description: For further documentation view the project-wiki (VPN connection is needed)
  url: 'https://10.18.205.252/doku.php?id=start&do=index'
servers:
  - url: 'http://localhost:8080/'
tags:
  - name: communication-session
    description: A ISO-15118 communication session
paths:
  /communication-session/test:
    get:
      tags:
        - test
      summary: Test the API connection
      operationId: getTest
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SessionId'
            application/json:
              schema:
                $ref: '#/components/schemas/SessionId'
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      x-codegen-request-body-name: body
  /communication-session:
    get:
      tags:
        - communication-session
      summary: Generate a new communication session
      operationId: addCommunicationSession
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SessionId'
            application/json:
              schema:
                $ref: '#/components/schemas/SessionId'
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      x-codegen-request-body-name: body
  /communication-session/findByStatus:
    get:
      tags:
      - communication-session
      summary: "Finds Sessions by their status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "findCommunicationSessionByStatus"
      parameters:
      - name: status
        in: query
        description: Status values that need to be considered for filter
        required: true
        style: form
        explode: true
        schema:
          $ref: '#/components/schemas/Status'
      responses:
        '200':
          description: "successful operation"
          content:
            application/xml:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id: 
                      $ref: '#/components/schemas/SessionId'
                    status:
                      $ref: '#/components/schemas/Status'
            application/json:
              schema:
                $ref: '#/components/schemas/SessionId'
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /communication-session/{session-id}/charge-parameter:
    get: 
      tags:
        - communication-session charge-parameter
      summary: Get the currently set charge parameters
      parameters:
        - name: session-id
          in: path
          required: true
          description: The id of the V2G communication session.
          schema:
            $ref: '#/components/schemas/SessionId'
      responses:  
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Charge-Parameter"
            application/xml:
              schema:
                $ref: '#/components/schemas/Charge-Parameter'
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      x-codegen-request-body-name: body
    post:
      tags:
        - communication-session charge-parameter
      summary: Create new charge parameters for a specific V2G communication session
      parameters:
        - name: session-id
          in: path
          required: true
          description: The id of the V2G communication session.
          schema:
            $ref: '#/components/schemas/SessionId'
      requestBody:
        description: A set of charge parameters for AC or DC charging
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Charge-Parameter'
          application/xml:
            schema:
              $ref: '#/components/schemas/Charge-Parameter'
        required: true
      responses:
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      x-codegen-request-body-name: body
    put: 
      tags:
        - communication-session charge-parameter
      summary: Update the charge parameters for a specific V2G communication session
      parameters:
        - name: session-id
          in: path
          required: true
          description: The id of the V2G communication session.
          schema:
            $ref: '#/components/schemas/SessionId'
      requestBody:
        description: A set of charge parameters for AC or DC charging
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Charge-Parameter'
          application/xml:
            schema:
              $ref: '#/components/schemas/Charge-Parameter'
        required: true
      responses:
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      x-codegen-request-body-name: body
  /communication-session/{session-id}/schedule:
    get: 
      tags:
        - communication-session schedule
      summary: Get the currently set charge schedule
      parameters:
        - name: session-id
          in: path
          required: true
          description: The id of the V2G communication session.
          schema:
            $ref: '#/components/schemas/SessionId'
      responses:  
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SASchedule"
            application/xml:
              schema:
                $ref: '#/components/schemas/SASchedule'
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
      x-codegen-request-body-name: body
  /communication-session/{session-id}/status:
    get:
      tags:
        - communication-session status
      summary: Get the current status of the communication session.
      parameters:
        - name: session-id
          in: path
          required: true
          description: The id of the V2G communication session.
          schema:
            $ref: '#/components/schemas/SessionId'
      responses:  
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Status"
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"    
    put:
      tags:
        - communication-session status
      summary: Change the status to 'paused' for a given time interval.
      parameters:
        - name: session-id
          in: path
          required: true
          description: The id of the V2G communication session.
          schema:
            $ref: '#/components/schemas/SessionId'
      requestBody:
        description: A time interval, by which the status is set to 'paused'. The time interval must not exceed 24h!
        content:
          application/json:
            schema:
              type: object
              properties:
                duration:
                  type: object
                  properties:
                    hours:
                      type: integer
                    minutes:
                      type: integer
                    seconds:
                      type: integer
      responses:
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    SessionId:
      type: string
      description: This message element is used by EVCC and SECC for uniquely identifying a V2G communication session. See section 8.4.2 of the ISO-15118-2 document for further information.
    Status:
      type: string
      description: The current status of a charging session.
      enum:
        - Charging
        - Paused
        - Stoped
    Charge-Parameter:
      type: object
      properties:
        ac-charge-parameter:
          type: object
          required:
            - nominal-voltage
            - max-current
          properties:
            nominal-voltage:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
            max-current:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
        dc-charge-parameter:
          type: object
          required:
            - max-current-limit
            - max-power-limit
            - max-voltage-limit
            - min-voltage-limit
            - min-current-limit
            - peak-current-ripple
          properties:
            max-current-limit:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
            max-power-limit:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
            max-voltage-limit:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
            min-current-limit:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
            min-voltage-limit:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
            current-regulation-tolerance:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
            peak-current-ripple:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
            energy-to-be-delivered:
              $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
      minProperties: 1
      maxProperties: 1
      additionalProperties: false
    SASchedule:
      required:
        - p_max_schedule
      type: object
      properties:
        p_max_schedule:
          type: array
          items:
            properties:
              p_max_schedule_entry:
                $ref: '#/components/schemas/Wallbox-API-Physical-Value-Type'
    Wallbox-API-Physical-Value-Type:
      type: object
      properties:
        multiplier:
          type: integer
        value:
          type: integer
        unit:
          type: string
          enum:
            - V
            - A
            - W
            - Wh
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
          scopes:
            'write:pets': modify pets in your account
            'read:pets': read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
